version: '3.3'

volumes:
  pg_data:    
  static:
  media:
  static_frontend:
  
services:
  db:
    image: postgres:13.10
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data/
  
  backend:
    build: ../backend/
    env_file: .env
    environment:
      - GUNICORN_TIMEOUT=120
    volumes:
      - static:/app/backend_static/
      - media:/app/media/
    depends_on:
      - db

  frontend:
    env_file: .env
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - static_frontend:/app/result_build/
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3    
    ports:
      - 9000:80
    env_file: .env
    volumes:
      - media:/media/
      - static:/backend_static/
      - static_frontend:/static_frontend/
      - ../docs/:/usr/share/nginx/html/api/docs/  
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
